### ISSUE TITLE
Build environment in docker

### ISSUE THREAD

**Issue by MatthiasLohr** [SynologyOpenSource/pkgscripts-ng#16]
Hello,

is there any reason why you do not use Docker for the build environment? If I would create a pull requests which adds docker support to this toolkit, how are the chances to get this pull request accepted (I do not want to waste my time on things that will be ignored)?

Best regards
Matthias

**Comment by niklaas** [comment]
Probably it's even easier to rely on this project: https://github.com/SynoCommunity/spksrc .

**Comment by MatthiasLohr** [comment]
Yeah, probably.
