### ISSUE TITLE
macOS: "tar: Option -L is not permitted in mode -x"

### ISSUE THREAD

**Issue by LukasBombach** [SynologyOpenSource/pkgscripts-ng#18]
I just cloned this repository and ran

```console
$ ./EnvDeploy -v 6.0 -p x64
```

But I am receiving the error 

```
tar -xhf /Users/lbombach/Projekte/synology-paperless/toolkit_tarballs/base_env-6.0.txz -C /Users/lbombach/Projekte/synology-paperless/build_env/ds.x64-6.0
tar: Option -L is not permitted in mode -x
```

…followed by a stacktrace

Not sure what I can do. I am using macOS Mojave 10.14.3

**Comment by ChangMM** [comment]
The same error

**Comment by Lord-Kamina** [comment]
Hey guys, I've never used Synology but I found this issue while looking how to solve the same error. It's an incompatibility between Linux and macOS, which by default uses bsdtar...

In macOS, `-h`is an alias for `-L`; instead, one should use `-H` which is the switch for dereference on mac.

**Comment by bonatoc** [comment]
You may want to use `gtar` if the above didn't made it for you:

`brew install gnu-tar`

as per this on StackEchange's [superuser.com link](https://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt).

**Comment by LukasBombach** [comment]
All of this sounds good, imma close this issue on behalf of the maintainer
