### ISSUE TITLE
Errors when installing platform

### ISSUE THREAD

**Issue by saxicek** [SynologyOpenSource/pkgscripts-ng#6]
I am trying to make toolkit working for Armada XP. Using Ubuntu as host operating system. I created toolkit in my home folder:
```
$ mkdir toolkit
$ cd ~/toolkit
$ git clone https://github.com/SynologyOpenSource/pkgscripts-ng pkgscripts
$ cd pkgscripts
$ ./EnvDeploy -v 6.1 -p armadaxp
```
But the EnvDeploy fails as it tries when untaring:
```
...
tar: dev/vbi2: Cannot mknod: Operation not permitted
tar: dev/sdy3: Cannot mknod: Operation not permitted
tar: dev/sdip12: Cannot mknod: Operation not permitted
tar: Exiting with failure status due to previous errors
```
Why is it trying to modify `dev`? Do I need to run the EnvDeploy as root (sudo)?

**Comment by SynologyOpenSource** [comment]
Hi @saxicek,

Yes, you need the root permission to run all pkgscripts-ng scripts.

Thanks for your reply.

**Comment by pntzio** [comment]
Is `dev` even needed for the sysroot?
Skipping it would allow non-privileged users to do this.
