### ISSUE TITLE
SynoBuild not Found

### ISSUE THREAD

**Issue by andre2308** [SynologyOpenSource/pkgscripts-ng#7]
Hey, when i try to compile minimalPkg or HelloKernel i get follow issue:

`
============================================================
                   Parse argument result                    
------------------------------------------------------------
env_section  : default
env_version  : None
dep_level    : 1
branch       : master
suffix       : 
collect      : True
update       : True
link         : True
build        : True
install      : True
only_install : False
sign         : True
build_opt    : 
install_opt  : 
print_log    : False
sdk_ver      : 6.0
package      : HelloKernel

Processing [6.1-15152]: monaco

============================================================
              Start to run "Traverse project"               
------------------------------------------------------------
[INFO] Branch projects: HelloKernel
[INFO] Tag projects: 
[INFO] Reference projects: 
[INFO] Reference tag projects: 

============================================================
                Start to run "Link Project"                 
------------------------------------------------------------
Link /toolkit/pkgscripts_ng -> /toolkit/build_env/ds.monaco-6.1/pkgscripts_ng
Link /toolkit/source/HelloKernel -> /toolkit/build_env/ds.monaco-6.1/source/HelloKernel

============================================================
                Start to run "Build Package"                
------------------------------------------------------------
[monaco] set -o pipefail; env PackageName=HelloKernel /toolkit/pkgscripts_ng/SynoBuild --monaco -c --min-sdk 6.0 HelloKernel 2>&1 | tee logs.build
Traceback (most recent call last):
  File "pkgscripts_ng/PkgCreate.py", line 409, in run_command
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -o pipefail; env PackageName=HelloKernel /toolkit/pkgscripts_ng/SynoBuild --monaco -c --min-sdk 6.0 HelloKernel 2>&1 | tee logs.build' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/toolkit/pkgscripts_ng/include/python/parallel.py", line 12, in __call__
    result = self.__callable(*args, **kwargs)
  File "pkgscripts_ng/PkgCreate.py", line 414, in run_command
BuildPackageError: set -o pipefail; env PackageName=HelloKernel /toolkit/pkgscripts_ng/SynoBuild --monaco -c --min-sdk 6.0 HelloKernel 2>&1 | tee logs.build failed. 
 Error log: /toolkit/build_env/ds.monaco-6.1/logs.build

[91mBuildPackageError:[0m
set -o pipefail; env PackageName=HelloKernel /toolkit/pkgscripts_ng/SynoBuild --monaco -c --min-sdk 6.0 HelloKernel 2>&1 | tee logs.build failed. 
 Error log: /toolkit/build_env/ds.monaco-6.1/logs.build

[ERROR] pkgscripts_ng/PkgCreate.py -p monaco -c HelloKernel failed!`

and build.log says:

`env: /pkgscripts_ng/SynoBuild: No such file or directory`

I set my Enviroment as discriped in the Manual at ~/toolkit

**Comment by SynologyOpenSource** [comment]
Hello,

I guess you have some changes your local project.

> [monaco] set -o pipefail; env PackageName=HelloKernel **/toolkit/pkgscripts_ng/SynoBuild** --monaco -c --min-sdk 6.0 HelloKernel 2>&1 | tee logs.build

It is supposed to be "pkgscripts-ng/SynoBuild" but not "/toolkit/pkgscripts_ng/SynoBuild".
Please remove the changes and try to build it again.
